export const albums = [
    { position: 1, artist: 'Nirvana', album: 'Nevermind', year: 1991, cover: 'nirvananevermind.jpeg', color: '#0066B1' },
    { position: 2, artist: 'Metallica', album: 'Master of Puppets', year: 1986, cover: 'metallicamasterofpuppets.jpeg', color: '#330D0A' },
    { position: 3, artist: 'System of a Down', album: 'Toxicity', year: 2001, cover: 'soadtoxicity.jpeg', color: '#BB3932' },
    { position: 4, artist: 'Don Broco', album: 'Technology', year: 2018, cover: 'donbrocotechnology.jpeg', color: '#BDA24E' },
    { position: 5, artist: 'Eminem', album: 'The Marshall Mathers LP', year: 2000, cover: 'eminemthemarshallmatherslp.jpeg', color: '#484644' },
    { position: 6, artist: 'Funeral for a Friend', album: 'Casually Dressed & Deep in Conversation', year: 2003, cover: 'ffafcasuallydressed.jpeg', color: '#000F26' },
    { position: 7, artist: 'My Chemical Romance', album: 'The Black Parade', year: 2006, cover: 'mcrtheblackparade.jpeg', color: '#E4E0E0' },
    { position: 8, artist: 'Queens of the Stone Age', album: 'Rated R', year: 2000, cover: 'qotsaratedr.png', color: '#006FBE' },
    { position: 9, artist: 'Radiohead', album: 'OK Computer', year: 1997, cover: 'radioheadokcomputer.jpg', color: '#A7BED5' },
    { position: 10, artist: 'Rage Against the Machine', album: 'Rage Against the Machine', year: 1992, cover: 'ratm.jpeg', color: '#141419' },
    { position: 11, artist: 'Blink 182', album: 'Blink 182', year: 2003, cover: 'blink182.jpeg', color: '#25AFA5' },
    { position: 12, artist: 'Type O Negative', album: 'October Rust', year: 1996, cover: 'tonoctoberrust.jpeg', color: '#889F71' },
    { position: 13, artist: 'Pink Floyd', album: 'Wish You Were Here', year: 1975, cover: 'pinkfloydwywh.png', color: '#FFFFFF' },
    { position: 14, artist: 'Funeral for a Friend', album: 'Hours', year: 2005, cover: 'ffafhours.jpg', color: '#060606' },
    { position: 15, artist: 'Linkin Park', album: 'Meteora', year: 2003, cover: 'linkinparkmeteora.jpeg', color: '#090909' },
    { position: 16, artist: 'Depeche Mode', album: 'Violator', year: 1990, cover: 'depechemodeviolator.png', color: '#85171A' },
    { position: 17, artist: 'Tool', album: '10,000 Days', year: 2006, cover: 'tool10000days.jpeg', color: '#222330' },
    { position: 18, artist: 'Marmozets', album: 'The Weird and Wonderful Marmozets', year: 2014, cover: 'weirdandwonderfulmarmozets.jpeg', color: '#CFA646' },
    { position: 19, artist: 'Turnstile', album: 'Glow On', year: 2021, cover: 'turnstileglowon.jpeg', color: '#F8DEE1' },
    { position: 20, artist: 'Bring Me The Horizon', album: 'Sempiternal', year: 2013, cover: 'bmthsempiternal.jpg', color: '#8D6138' },
    { position: 21, artist: 'Nirvana', album: 'In Utero', year: 1993, cover: 'nirvanainutero.jpeg', color: '#FDFBD8' },
    { position: 22, artist: 'Against Me!', album: 'Transgender Dysphoria Blues', year: 2014, cover: 'againstmetdb.jpeg', color: '#FFFFFF' },
    { position: 23, artist: 'Nine Inch Nails', album: 'Pretty Hate Machine', year: 1989, cover: 'ninphm.png', color: '#1676A0' },
    { position: 24, artist: 'Pixies', album: 'Doolittle', year: 1989, cover: 'pixiesdoolittle.jpeg', color: '#544133' },
    { position: 25, artist: 'Queens of the Stone Age', album: 'Songs for the Deaf', year: 2002, cover: 'qotsasongsforthedeaf.png', color: '#CC222B' },
    { position: 26, artist: 'System of a Down', album: 'System of a Down', year: 1998, cover: 'soad.jpeg', color: '#090909' },
    { position: 27, artist: 'Tool', album: 'Ænima', year: 1996, cover: 'toolaenima.jpeg', color: '#FEFEFE' },
    { position: 28, artist: 'Pearl Jam', album: 'Ten', year: 1991, cover: 'pearljamten.jpg', color: '#892B44' },
    { position: 29, artist: 'Rolo Tomassi', album: 'Time Will Die and Love Will Bury It', year: 2018, cover: 'rolotomassitwdalwbi.jpeg', color: '#707070' },
    { position: 30, artist: 'Deftones', album: 'White Pony', year: 2000, cover: 'deftoneswhitepony.jpeg', color: '#C1C3C0' },
    { position: 31, artist: 'Red Hot Chili Peppers', album: 'Californication', year: 1999, cover: 'rhcpcalifornication.jpeg', color: '#A40101' },
    { position: 32, artist: 'Manic Street Preachers', album: 'The Holy Bible', year: 1994, cover: 'msptheholybible.jpeg', color: '#FFFFFA' },
    { position: 33, artist: 'Faith No More', album: 'The Real Thing', year: 1989, cover: 'fnmtherealthing.jpeg', color: '#B19197' },
    { position: 34, artist: 'InMe', album: 'White Butterfly', year: 2005, cover: 'inmewhitebutterfly.jpg', color: '#DD2E34' },
    { position: 35, artist: 'Kyuss', album: 'Welcome to Sky Valley', year: 1994, cover: 'kyussskyvalley.jpg', color: '#050507' },
    { position: 36, artist: 'Weezer', album: 'Weezer (The Blue Album)', year: 1994, cover: 'weezerbluealbum.jpg', color: '#009BD3' },
    { position: 37, artist: 'Bloc Party', album: 'Silent Alarm', year: 2005, cover: 'blocpartysilentalarm.jpeg', color: '#FFFFFF' },
    { position: 38, artist: 'Alice in Chains', album: 'Dirt', year: 1992, cover: 'aicdirt.jpeg', color: '#F74101' },
    { position: 39, artist: 'Limp Bizkit', album: 'Chocolate Starfish and the Hot Dog Flavoured Water', year: 2000, cover: 'limpbizkit.jpeg', color: '#090909' },
    { position: 40, artist: 'Blink 182', album: 'Take Off Your Pants and Jacket', year: 2001, cover: 'blink182toypaj.jpeg', color: '#090909' },
    { position: 41, artist: 'Linkin Park', album: 'Hybrid Theory', year: 2000, cover: 'lphybridtheory.jpeg', color: '#969690' },
    { position: 42, artist: 'Arctic Monkeys', album: `Whatever People Say I Am, That's What I'm Not`, year: 2006, cover: 'arcticmonkeys.jpeg', color: '#272727' },
    { position: 43, artist: 'Ghost', album: 'Meliora', year: 2015, cover: 'ghostmeliora.jpeg', color: '#4D2720' },
    { position: 44, artist: 'The Mars Volta', album: 'Frances the Mute', year: 2005, cover: 'marsvoltafrancesthemute.png', color: '#7E1619' },
    { position: 45, artist: 'My Chemical Romance', album: 'Three Cheers For Sweet Revenge', year: 2004, cover: 'mcrthreecheers.png', color: '#B53A37' },
    { position: 46, artist: 'Jamie Lenman', album: 'Devolver', year: 2017, cover: 'jamielenman.jpeg', color: '#590D11' },
    { position: 47, artist: 'Red Hot Chili Peppers', album: 'Blood Sugar Sex Magik', year: 1991, cover: 'rhcpbssm.jpeg', color: '#972126' },
    { position: 48, artist: 'Metallica', album: 'Metallica (The Black Album)', year: 1991, cover: 'metallicablackalbum.jpg', color: '#040A0A' },
    { position: 49, artist: 'Machine Head', album: 'The Blackening', year: 2007, cover: 'machineheadtheblackening.jpeg', color: '#090909' },
    { position: 50, artist: 'Nirvana', album: 'Bleach', year: 1989, cover: 'nirvanableach.jpg', color: '#090909' },
    { position: 51, artist: 'Avenged Sevenfold', album: 'City of Evil', year: 2005, cover: 'a7xcityofevil.jpeg', color: '#0A080F' },
    { position: 52, artist: 'Cult of Luna & Julie Christmas', album: 'Mariner', year: 2016, cover: 'cultoflunamariner.jpeg', color: '#37AC7B' },
    { position: 53, artist: 'InMe', album: 'Overgrown Even', year: 2003, cover: 'inmeovergrowneden.jpg', color: '#AEBE9C' },
    { position: 54, artist: 'Slipknot', album: 'Vol 3: (The Subliminal Verses)', year: 2004, cover: 'slipknotvol3.png', color: '#CF4414' },
    { position: 55, artist: 'Foo Fighters', album: 'The Colour and the Shape', year: 1997, cover: 'foofighterscolorandshape.jpeg', color: '#2B3449' },
    { position: 56, artist: 'Radiohead', album: 'The Bends', year: 1995, cover: 'radioheadthebends.png', color: '#020001' },
    { position: 57, artist: 'Blink 182', album: 'Enema of the State', year: 1999, cover: 'blink182enema.jpeg', color: '#41B2FF' },
    { position: 58, artist: 'Enter Shikari', album: 'The Spark', year: 2017, cover: 'entershikarithespark.jpeg', color: '#9AC7D4' },
    { position: 59, artist: 'Bullet for my Valentine', album: 'The Poison', year: 2005, cover: 'bfmvthepoison.jpeg', color: '#A42633' },
    { position: 60, artist: 'Avenged Sevenfold', album: 'Life is But a Dream...', year: 2023, cover: 'a7xlibad.jpeg', color: '#DECCBA' },
    { position: 61, artist: 'Type O Negative', album: 'Bloody Kisses', year: 1993, cover: 'typeonegativebloodykisses.jpeg', color: '#80A594' },
    { position: 62, artist: 'Pink Floyd', album: 'The Dark Side of the Moon', year: 1973, cover: 'pinkfloyddarksidemoon.jpeg', color: '#000103' },
    { position: 63, artist: 'Marina & the Diamonds', album: 'The Family Jewels', year: 2010, cover: 'marina.png', color: '#847958' },
    { position: 64, artist: 'Trophy Eyes', album: 'Chemical Miracle', year: 2016, cover: 'trophyeyes.jpeg', color: '#66C7F0' },
    { position: 65, artist: 'Dan le Sac vs Scroobius Pip', album: 'Angles', year: 2008, cover: 'dlsvssp.jpeg', color: '#8FCCC6' },
    { position: 66, artist: 'Enter Shikari', album: 'Take to the Skies', year: 2007, cover: 'entershikaritaketotheskies.jpg', color: '#98A577' },
    { position: 67, artist: 'Korn', album: 'Issues', year: 1999, cover: 'kornissues.jpg', color: '#D1BF7F' },
    { position: 68, artist: 'Alcest', album: 'Spiritual Instinct', year: 2019, cover: 'alcestspiritualinstinct.jpeg', color: '#181C27' },
    { position: 69, artist: 'Maybeshewill', album: 'Not for Want of Trying', year: 2008, cover: 'maybeshewill.jpeg', color: '#372228' },
    { position: 70, artist: 'The Beatles', album: 'Abbey Road', year: 1969, cover: 'thebeatlesabbeyroad.jpeg', color: '#ABDCF6' },
    { position: 71, artist: 'Architects', album: 'All Our Gods Have Abandoned Us', year: 2016, cover: 'architectsaoghau.jpeg', color: '#D8D8D8' },
    { position: 72, artist: `Guns N' Roses`, album: 'Appetite for Destruction', year: 1987, cover: 'gunsnroses.jpg', color: '#090909' },
    { position: 73, artist: 'Heck', album: 'Instructions', year: 2016, cover: 'heckinstructions.jpeg', color: '#2E2B26' },
    { position: 74, artist: 'Against Me!', album: 'White Crosses', year: 2010, cover: 'againstmewhitecrosses.jpeg', color: '#D60A0F' },
    { position: 75, artist: 'Creeper', album: 'Sex, Death and the Infinite Void', year: 2020, cover: 'creepersdativ.jpeg', color: '#E2E2E2' },
    { position: 76, artist: 'Nine Inch Nails', album: 'The Downward Spiral', year: 1994, cover: 'ninthedownwardspiral.png', color: '#F2E6B7' },
    { position: 77, artist: 'Duran Duran', album: 'Rio', year: 1982, cover: 'duranrio.jpeg', color: '#840B45' },
    { position: 78, artist: 'Black Peaks', album: 'Statues', year: 2016, cover: 'blackpeaksstatues.png', color: '#0F0F0F' },
    { position: 79, artist: 'Slipknot', album: 'IOWA', year: 2001, cover: 'slipknotiowa.jpeg', color: '#EDF5F0' },
    { position: 80, artist: 'Tool', album: 'Lateralus', year: 2001, cover: 'toollateralus.jpeg', color: '#C26572' },
    { position: 81, artist: 'Of Monsters and Men', album: 'My Head is an Animal', year: 2011, cover: 'omam.jpeg', color: '#616854' },
    { position: 82, artist: 'Pulp', album: 'Different Class', year: 1995, cover: 'pulpdifferentclass.png', color: '#03252A' },
    { position: 83, artist: 'Kyuss', album: 'Blues for the Red Sun', year: 1992, cover: 'kyussblues.jpeg', color: '#B6281C' },
    { position: 84, artist: 'The Mars Volta', album: 'Deloused in the Comatorium', year: 2003, cover: 'marsvoltadeloused.jpeg', color: '#D8C270' },
    { position: 85, artist: 'Slipknot', album: 'Slipknot', year: 1999, cover: 'slipknot.jpeg', color: '#B5321E' },
    { position: 86, artist: 'Ithaca', album: 'They Fear Us', year: 2022, cover: 'ithacatheyfearus.png', color: '#F88B40' },
    { position: 87, artist: 'System of a Down', album: 'Hypnotize', year: 2005, cover: 'soadhypnotize.jpeg', color: '#7484BE' },
    { position: 88, artist: 'Korn', album: 'Korn', year: 1994, cover: 'korn.jpeg', color: '#55160F' },
    { position: 89, artist: 'Idles', album: 'Joy as an Act of Resistance', year: 2018, cover: 'idles.jpeg', color: '#B08F30' },
    { position: 90, artist: 'Baroness', album: 'Purple', year: 2016, cover: 'baronesspurple.jpeg', color: '#725FBD' },
    { position: 91, artist: 'Faith No More', album: 'King for a Day... Fool for a Lifetime', year: 1995, cover: 'fnmking.png', color: '#FF0000' },
    { position: 92, artist: 'Depeche Mode', album: 'Music for the Masses', year: 1987, cover: 'depechemodemusicforthemasses.png', color: '#D2C497' },
    { position: 93, artist: 'Killswitch Engage', album: 'The End of Heartache', year: 2004, cover: 'kseendofheartache.jpeg', color: '#9A2A2C' },
    { position: 94, artist: 'Duran Duran', album: 'Duran Duran (The Wedding Album)', year: 1993, cover: 'duranduran.jpeg', color: '#787375' },
    { position: 95, artist: 'Black Sabbath', album: 'Master of Reality', year: 1971, cover: 'blacksabbath.jpeg', color: '#673093' },
    { position: 96, artist: 'Gold Key', album: 'Panic Machine', year: 2020, cover: 'goldkey.jpeg', color: '#BFBBB0' },
    { position: 97, artist: 'Kate Bush', album: 'Hounds of Love', year: 1985, cover: 'katebushhoundsoflove.png', color: '#FFFFFF' },
    { position: 98, artist: 'Letlive.', album: 'If I\'m the Devil...', year: 1996, cover: 'letlive.jpg', color: '#FFE0EB' },
    { position: 99, artist: 'Creeper', album: 'Sanguivore', year: 2023, cover: 'creepersanguivore.jpeg', color: '#CFBC96' },
    { position: 100, artist: 'Senser', album: 'Stacked Up', year: 1994, cover: 'senser.jpeg', color: '#2D2265' },
    // { position: 98, artist: 'Placebo', album: 'Placebo', year: 1996, cover: 'placebo.jpeg', color: '#4B9B9F' },
     // { position: 90, artist: 'Avenged Sevenfold', album: 'The Stage', year: 2016, cover: 'a7xthestage.jpeg', color: '#0D0A0F' },
    // { position: 0o0, artist: 'Fugazi', album: '13 Songs', year: 1989, cover: 'fugazi.png', color: '#B60000' },
    // { position: 0o0, artist: 'Mr Scruff', album: 'Keep It Unreal', year: 1999, cover: 'mrscruff.jpeg', color: '#2A185B' },
    // { position: 0o0, artist: 'Rammstein', album: 'Mutter', year: 2001, cover: 'rammsteinmutter.jpeg', color: '#A9A783' },
    // { position: 0o0, artist: 'Audioslave', album: 'Audioslave', year: 2002, cover: 'audioslave.jpeg', color: '#AABADC' },
    // { position: 0o0, artist: 'Rise Against', album: 'Revolutions Per Minute', year: 2003, cover: 'riseagainst.jpeg', color: '#E7E9F4' },
    // { position: 0o0, artist: 'Incubus', album: 'Morning View', year: 2001, cover: 'incubusmorningview.jpeg', color: '#B7D5ED' },
    // { position: 0o0, artist: 'Hundred Reasons', album: 'Ideas Above Our Station', year: 2002, cover: 'hundredreasons.jpeg', color: '#31444C' },
    // { position: 0o0, artist: 'Fleetwood Mac', album: 'Rumours', year: 1977, cover: 'fleetwoodmac.jpg', color: '#FAEED8' },
    // { position: 82, artist: 'Against Me!', album: 'New Wave', year: 2007, cover: 'againstmenewwave.jpeg', color: '#090909' },
    // { position: 89, artist: 'Brand New', album: 'Science Fiction', year: 2017, cover: 'brandnewsciencefiction.png', color: '#000000' },


]