export const albums = [
    { position: 1, artist: 'Nirvana', album: 'Nevermind', year: 1991, cover: 'nirvananevermind.jpeg' },
    { position: 2, artist: 'Metallica', album: 'Master of Puppets', year: 1986, cover: 'metallicamasterofpuppets.jpeg' },
    { position: 3, artist: 'System of a Down', album: 'Toxicity', year: 2001, cover: 'soadtoxicity.jpeg' },
    { position: 4, artist: 'Eminem', album: 'The Marshall Mathers LP', year: 2000, cover: 'eminemthemarshallmatherslp.jpeg' },
    { position: 5, artist: 'Don Broco', album: 'Technology', year: 2018, cover: 'donbrocotechnology.jpeg' },
    { position: 6, artist: 'Funeral for a Friend', album: 'Casually Dressed & Deep in Conversation', year: 2003, cover: 'ffafcasuallydressed.jpeg' },
    { position: 7, artist: 'My Chemical Romance', album: 'The Black Parade', year: 2006, cover: 'mcrtheblackparade.jpeg' },
    { position: 8, artist: 'Queens of the Stone Age', album: 'Rated R', year: 2000, cover: 'qotsaratedr.png' },
    { position: 9, artist: 'Funeral for a Friend', album: 'Hours', year: 2005, cover: 'ffafhours.jpg' },
    { position: 10, artist: 'Radiohead', album: 'OK Computer', year: 1997, cover: 'radioheadokcomputer.jpg' },
    { position: 11, artist: 'Rage Against the Machine', album: 'Rage Against the Machine', year: 1992, cover: 'ratm.jpeg' },
    { position: 12, artist: 'Blink 182', album: 'Blink 182', year: 2003, cover: 'blink182.jpeg' },
    { position: 13, artist: 'Rolo Tomassi', album: 'Time Will Die and Love Will Bury It', year: 2018, cover: 'rolotomassitwdalwbi.jpeg' },
    { position: 14, artist: 'Pink Floyd', album: 'Wish You Were Here', year: 1975, cover: 'pinkfloydwywh.png' },
    { position: 15, artist: 'Nine Inch Nails', album: 'Pretty Hate Machine', year: 1989, cover: 'ninphm.png' },
    { position: 16, artist: 'Pixies', album: 'Doolittle', year: 1989, cover: 'pixiesdoolittle.jpeg' },
    { position: 17, artist: 'Against Me!', album: 'Transgender Dysphoria Blues', year: 2014, cover: 'againstmetdb.jpeg' },
    { position: 18, artist: 'Linkin Park', album: 'Meteora', year: 2003, cover: 'linkinparkmeteora.jpeg' },
    { position: 19, artist: 'Type O Negative', album: 'October Rust', year: 1996, cover: 'tonoctoberrust.jpeg' },
    { position: 20, artist: 'Tool', album: '10,000 Days', year: 2006, cover: 'tool10000days.jpeg' },
    { position: 21, artist: 'Nirvana', album: 'In Utero', year: 1993, cover: 'nirvanainutero.jpeg' },
    { position: 22, artist: 'Marmozets', album: 'The Weird and Wonderful Marmozets', year: 2014, cover: 'weirdandwonderfulmarmozets.jpeg' },
    { position: 23, artist: 'Red Hot Chili Peppers', album: 'Californication', year: 1999, cover: 'rhcpcalifornication.jpeg' },
    { position: 24, artist: 'Queens of the Stone Age', album: 'Songs for the Deaf', year: 2002, cover: 'qotsasongsforthedeaf.png' },
    { position: 25, artist: 'System of a Down', album: 'System of a Down', year: 1998, cover: 'soad.jpeg' },
    { position: 26, artist: 'Tool', album: 'Ænima', year: 1996, cover: 'toolaenima.jpeg' },
    { position: 27, artist: 'InMe', album: 'White Butterfly', year: 2005, cover: 'inmewhitebutterfly.jpg' },
    { position: 28, artist: 'Pearl Jam', album: 'Ten', year: 1991, cover: 'pearljamten.jpg' },
    { position: 29, artist: 'Faith No More', album: 'The Real Thing', year: 1989, cover: 'fnmtherealthing.jpeg' },
    { position: 30, artist: 'Kyuss', album: 'Welcome to Sky Valley', year: 1994, cover: 'kyussskyvalley.jpg' },
    { position: 31, artist: 'Weezer', album: 'Weezer (The Blue Album)', year: 1994, cover: 'weezerbluealbum.jpg' },
    { position: 32, artist: 'Bloc Party', album: 'Silent Alarm', year: 2005, cover: 'blocpartysilentalarm.jpeg' },
    { position: 33, artist: 'Limp Bizkit', album: 'Chocolate Starfish and the Hot Dog Flavoured Water', year: 2000, cover: 'limpbizkit.jpeg' },
    { position: 34, artist: 'Deftones', album: 'White Pony', year: 2000, cover: 'deftoneswhitepony.jpeg' },
    { position: 35, artist: 'Dan le Sac vs Scroobius Pip', album: 'Angles', year: 2008, cover: 'dlsvssp.jpeg' },
    { position: 36, artist: 'Blink 182', album: 'Take Off Your Pants and Jacket', year: 2001, cover: 'blink182toypaj.jpeg' },
    { position: 37, artist: 'Alice in Chains', album: 'Dirt', year: 1992, cover: 'aicdirt.jpeg' },
    { position: 38, artist: 'Linkin Park', album: 'Hybrid Theory', year: 2000, cover: 'lphybridtheory.jpeg' },
    { position: 39, artist: 'Arctic Monkeys', album: `Whatever People Say I Am, That's What I'm Not`, year: 2006, cover: 'arcticmonkeys.jpeg' },
    { position: 40, artist: 'Metallica', album: 'Metallica (The Black Album)', year: 1991, cover: 'metallicablackalbum.jpg' },
    { position: 41, artist: 'Ghost', album: 'Meliora', year: 2015, cover: 'ghostmeliora.jpeg' },
    { position: 42, artist: 'Trophy Eyes', album: 'Chemical Miracle', year: 2016, cover: 'trophyeyes.jpeg' },
    { position: 43, artist: 'The Mars Volta', album: 'Frances the Mute', year: 2005, cover: 'marsvoltafrancesthemute.png' },
    { position: 44, artist: 'Jamie Lenman', album: 'Devolver', year: 2017, cover: 'jamielenman.jpeg' },
    { position: 45, artist: 'Red Hot Chili Peppers', album: 'Blood Sugar Sex Magik', year: 1991, cover: 'rhcpbssm.jpeg' },
    { position: 46, artist: 'Machine Head', album: 'The Blackening', year: 2007, cover: 'machineheadtheblackening.jpeg' },
    { position: 47, artist: 'Nirvana', album: 'Bleach', year: 1989, cover: 'nirvanableach.jpg' },
    { position: 48, artist: 'Avenged Sevenfold', album: 'City of Evil', year: 2005, cover: 'a7xcityofevil.jpeg' },
    { position: 49, artist: 'Rammstein', album: 'Mutter', year: 2001, cover: 'rammsteinmutter.jpeg' },
    { position: 50, artist: 'InMe', album: 'Overgrown Even', year: 2003, cover: 'inmeovergrowneden.jpg' },
    { position: 51, artist: 'Slipknot', album: 'Vol 3: (The Subliminal Verses)', year: 2004, cover: 'slipknotvol3.png' },
    { position: 52, artist: 'Foo Fighters', album: 'The Colour and the Shape', year: 1997, cover: 'foofighterscolorandshape.jpeg' },
    { position: 53, artist: 'Radiohead', album: 'The Bends', year: 1995, cover: 'radioheadthebends.png' },
    { position: 54, artist: 'Blink 182', album: 'Enema of the State', year: 1999, cover: 'blink182enema.jpeg' },
    { position: 55, artist: 'Enter Shikari', album: 'The Spark', year: 2017, cover: 'entershikarithespark.jpeg' },
    { position: 56, artist: 'Bullet for my Valentine', album: 'The Poison', year: 2005, cover: 'bfmvthepoison.jpeg' },
    { position: 57, artist: 'Cult of Luna & Julie Christmas', album: 'Mariner', year: 2016, cover: 'cultoflunamariner.jpeg' },
    { position: 58, artist: 'Pink Floyd', album: 'The Dark Side of the Moon', year: 1973, cover: 'pinkfloyddarksidemoon.jpeg' },
    { position: 59, artist: 'Marina & the Diamonds', album: 'The Family Jewels', year: 2010, cover: 'marina.png' },
    { position: 60, artist: 'Placebo', album: 'Placebo', year: 1996, cover: 'placebo.jpeg' },
    { position: 61, artist: 'System of a Down', album: 'Hypnotize', year: 2005, cover: 'soadhypnotize.jpeg' },
    { position: 62, artist: 'Manic Street Preachers', album: 'The Holy Bible', year: 1994, cover: 'msptheholybible.jpeg' },
    { position: 63, artist: 'Dr Dre', album: '2001', year: 1999, cover: 'drdre2001.jpeg' },
    { position: 64, artist: 'Korn', album: 'Issues', year: 1999, cover: 'kornissues.jpg' },
    { position: 65, artist: 'Alcest', album: 'Spiritual Instinct', year: 2019, cover: 'alcestspiritualinstinct.jpeg' },
    { position: 66, artist: 'Turnstile', album: 'Glow On', year: 2021, cover: 'turnstileglowon.jpeg' },
    { position: 67, artist: 'Maybeshewill', album: 'Not for Want of Trying', year: 2008, cover: 'maybeshewill.jpeg' },
    { position: 68, artist: 'My Chemical Romance', album: 'Three Cheers For Sweet Revenge', year: 2004, cover: 'mcrthreecheers.png' },
    { position: 69, artist: 'The Beatles', album: 'Abbey Road', year: 1969, cover: 'thebeatlesabbeyroad.jpeg' },
    { position: 70, artist: 'Audioslave', album: 'Audioslave', year: 2002, cover: 'audioslave.jpeg' },
    { position: 71, artist: 'Of Monsters and Men', album: 'My Head is an Animal', year: 2011, cover: 'omam.jpeg' },
    { position: 72, artist: `Guns N' Roses`, album: 'Appetite for Destruction', year: 1987, cover: 'gunsnroses.jpg' },
    { position: 73, artist: 'Heck', album: 'Instructions', year: 2016, cover: 'heckinstructions.jpeg' },
    { position: 74, artist: 'Creeper', album: 'Sex, Death and the Infinite Void', year: 2020, cover: 'creepersdativ.jpeg' },
    { position: 75, artist: 'Against Me!', album: 'White Crosses', year: 2010, cover: 'againstmewhitecrosses.jpeg' },
    { position: 76, artist: 'Nine Inch Nails', album: 'The Downward Spiral', year: 1994, cover: 'ninthedownwardspiral.png' },
    { position: 77, artist: 'Pulp', album: 'Different Class', year: 1995, cover: 'pulpdifferentclass.png' },
    { position: 78, artist: 'Black Peaks', album: 'Statues', year: 2016, cover: 'blackpeaksstatues.png' },
    { position: 79, artist: 'Slipknot', album: 'IOWA', year: 2001, cover: 'slipknotiowa.jpeg' },
    { position: 80, artist: 'Tool', album: 'Lateralus', year: 2001, cover: 'toollateralus.jpeg' },
    { position: 81, artist: 'Enter Shikari', album: 'Take to the Skies', year: 2007, cover: 'entershikaritaketotheskies.jpg' },
    { position: 82, artist: 'Kyuss', album: 'Blues for the Red Sun', year: 1992, cover: 'kyussblues.jpeg' },
    { position: 83, artist: 'The Mars Volta', album: 'Deloused in the Comatorium', year: 2003, cover: 'marsvoltadeloused.jpeg' },
    { position: 84, artist: 'Slipknot', album: 'Slipknot', year: 1999, cover: 'slipknot.jpeg' },
    { position: 85, artist: 'Against Me!', album: 'New Wave', year: 2007, cover: 'againstmenewwave.jpeg' },
    { position: 86, artist: 'Bring Me The Horizon', album: 'Sempiternal', year: 2013, cover: 'bmthsempiternal.jpg' },
    { position: 87, artist: 'Korn', album: 'Korn', year: 1994, cover: 'korn.jpeg' },
    { position: 88, artist: 'Biffy Clyro', album: 'Puzzle', year: 2007, cover: 'biffyclyropuzzle.jpg' },
    { position: 89, artist: 'Avenged Sevenfold', album: 'The Stage', year: 2016, cover: 'a7xthestage.jpeg' },
    { position: 90, artist: 'Baroness', album: 'Purple', year: 2016, cover: 'baronesspurple.jpeg' },
    { position: 91, artist: 'Faith No More', album: 'King for a Day... Fool for a Lifetime', year: 1995, cover: 'fnmking.png' },
    { position: 92, artist: 'Hundred Reasons', album: 'Ideas Above Our Station', year: 2002, cover: 'hundredreasons.jpeg' },
    { position: 93, artist: 'Rise Against', album: 'Revolutions Per Minute', year: 2003, cover: 'riseagainst.jpeg' },
    { position: 94, artist: 'Killswitch Engage', album: 'The End of Heartache', year: 2004, cover: 'kseendofheartache.jpeg' },
    { position: 95, artist: 'Fleetwood Mac', album: 'Rumours', year: 1977, cover: 'fleetwoodmac.jpg' },
    { position: 96, artist: 'Mr Scruff', album: 'Keep It Unreal', year: 1999, cover: 'mrscruff.jpeg' },
    { position: 97, artist: 'Jimmy Eat World', album: 'Bleed American', year: 2001, cover: 'jewbleedamerican.jpeg' },
    { position: 98, artist: 'Gold Key', album: 'Panic Machine', year: 2020, cover: 'goldkey.jpeg' },
    { position: 99, artist: 'Chase & Status', album: 'No More Idols', year: 2011, cover: 'chaseandstatus.jpeg' },
    { position: 100, artist: 'Incubus', album: 'Morning View', year: 2001, cover: 'incubusmorningview.jpeg' },
]